### ISSUE TITLE
ConnectionReset (os error 10054) on response

### ISSUE THREAD

**Issue by Guillaume-Lebegue** [zhmushan/abc#121]
Hello,
I'm using abc v1.2.4 with deno v1.6.3 on Window 10
And sometime when sending response the server crashes

Here the error
```
error: Uncaught (in promise) ConnectionReset: An existing connection was forcibly closed by the remote host. (os error 10054)
    at unwrapResponse (deno:runtime/js/10_dispatch_minimal.js:59:13)
    at sendAsync (deno:runtime/js/10_dispatch_minimal.js:98:12)
    at async read (deno:runtime/js/12_io.js:99:19)
    at async BufReader.read (bufio.ts:146:12)
    at async BufReader.readFull (bufio.ts:178:20)
    at async WireProtocol.receive (protocol.ts:79:28)
```

**Comment by zhmushan** [comment]
Can you provide code snippets?

**Comment by Guillaume-Lebegue** [comment]
Ok, So I found what was causing it.

Because of the error, I thought abc was the cause, but turn out that it was mongo when doing multiple database request.

Sorry for the inconvenience.
