### ISSUE TITLE
Update http package (0.3.1 to 0.3.2)

### ISSUE THREAD

**Issue by sundowndev** [zhmushan/abc#22]
Tried the code in doc

```ts
import { abc } from "https://deno.sh/abc@v0.1.0/mod.ts";

const app = abc();

app
  .get("/hello", c => {
    return "Hello, Abc!";
  })
  .start("0.0.0.0:8080");
```

Then run : 

```
$ deno test.ts
```

Get this error : 

```
Compiling file:///home/sundowndev/www/deno/test.ts
Downloading https://deno.land/x/http@v0.3.0/deno... NOT FOUND
Uncaught NotFound: Cannot resolve module "deno" from "/home/sundowndev/.cache/deno/deps/https/deno.land/x/http@v0.3.0/server.ts"
    at DenoError (deno/js/errors.ts:22:5)
    at maybeError (deno/js/errors.ts:33:12)
    at maybeThrowError (deno/js/errors.ts:39:15)
    at sendSync (deno/js/dispatch.ts:75:5)
    at fetchModuleMetaData (deno/js/os.ts:80:19)
    at _resolveModule (deno/js/compiler.ts:249:38)
    at resolveModuleNames (deno/js/compiler.ts:479:35)
    at compilerHost.resolveModuleNames (deno/third_party/node_modules/typescript/lib/typescript.js:118650:138)
    at resolveModuleNamesWorker (deno/third_party/node_modules/typescript/lib/typescript.js:86767:127)
    at resolveModuleNamesReusingOldState (deno/third_party/node_modules/typescript/lib/typescript.js:87001:24)
```

May be an issue with deno ?

deno: 0.3.3
v8: 7.4.238
typescript: 3.3.3333

**Comment by sundowndev** [comment]
Moved to https://github.com/denoland/deno_std/issues/296.

**Comment by sundowndev** [comment]
Founds out the issue. The example is using old package which is using old server package. https://deno.sh/abc@v0.1.0/package.ts

**Comment by zhmushan** [comment]
Hi, this problem has been fixed in https://github.com/zhmushan/abc/pull/21
You can use the master branch directly:
```ts
import { abc } from "https://deno.sh/abc/mod.ts"
```
