### ISSUE TITLE
Unable to close the server properly by calling .close()

### ISSUE THREAD

**Issue by motss** [zhmushan/abc#35]
Calling `.close()` throws an uncaught error. The following are the details about the error logged:

## Error message

```sh
Uncaught Other: Listener has been closed
    at DenoError (js/errors.ts:22:5)
    at maybeError (js/errors.ts:33:12)
    at handleAsyncMsgFromRust (js/dispatch.ts:41:17)
    at handleAsyncMsgFromRust (shared_queue.js:157:9)
```

## Minimal script to reproduce uncaught error

```ts
import { abc } from "./test.mod.ts";

const app = abc();

app.get("/", () => "Hello, World!");

app.start("0.0.0.0:8080");

/** Close server after 3 seconds */
setTimeout(() => app.close(), 3e3);

/** Simulate fake HTTP calls */
setInterval(async () => {
  const r = await fetch('http://127.0.0.1:8080');
  const d = await r.text();

  console.log('d', d);
}, 1e3);
```

## Platform

```sh
deno: 0.9.0
v8: 7.7.37
typescript: 3.5.1
os: Windows 10
```

**Comment by zhmushan** [comment]
https://github.com/denoland/deno_std/issues/465
No one noticed this issue (ಥ_ಥ)

**Comment by motss** [comment]
https://github.com/denoland/deno_std/issues/386 might be related too.

**Comment by zhmushan** [comment]
@motss This issue seems to have been fixed

**Comment by motss** [comment]
Okay. Thanks.
