### ISSUE TITLE
Stacktrace in case of error

### ISSUE THREAD

**Issue by AvnerCohen** [zhmushan/abc#74]
Apologies if this is too simple and basic, but couldn't quite get this covered from the docs.

In express, as an example, if I get an error on the route impl, I'll get an a full stack trace , for instance:

```
Example app listening at http://localhost:3000
ReferenceError: p is not defined
    at test/test.js:6:14
    at Layer.handle [as handle_request] (test/node_modules/express/lib/router/layer.js:95:5)
    at next (test/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (test/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (test/node_modules/express/lib/router/layer.js:95:5)
    at test/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (test/node_modules/express/lib/router/index.js:335:12)
    at next (test/node_modules/express/lib/router/index.js:275:10)
    at expressInit (test/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (test/node_modules/express/lib/router/layer.js:95:5)
```

On abc, I can't get beyond:
```
{"statusCode":500,"error":"Internal Server Error","message":"Cannot read property p of undefined"}
```

Is there any easy way to print the stack of all unhandled exceptions I am overlooking ?

**Comment by zhmushan** [comment]
Fixed in https://github.com/zhmushan/abc/commit/f6fbc3916fcc7fd59370ca2a4621b2d2185f0e4e
